### ISSUE TITLE
Error in Step 007 `Jacobi`

### ISSUE THREAD

**Issue by groponp** [fhh2626/BFEE2#103]
Hi, i'm getting following error in step 007: 

REINITIALIZING VELOCITIES AT STEP 500 TO 310 KELVIN.
TCL: Running for 5000000 steps
colvars: Too many iterations in routine jacobi.
colvars: This is usually the result of an ill-defined set of atoms for rotational alignment (RMSD, rotateReference, etc).
FATAL ERROR: Error in the collective variables module (see above for details)
FATAL ERROR: Error in the collective variables module (see above for details)
colvars: Too many iterations in routine jacobi.
colvars: This is usually the result of an ill-defined set of atoms for rotational alignment (RMSD, rotateReference, etc).
colvars: Too many iterations in routine jacobi.
colvars: This is usually the result of an ill-defined set of atoms for rotational alignment (RMSD, rotateReference, etc).
FATAL ERROR: Error in the collective variables module (see above for details)
FATAL ERROR: Error in the collective variables module (see above for details)
[Partition 0][Node 0] End of program
FATAL ERROR: Error in the collective variables module (see above for details)
colvars: Too many iterations in routine jacobi.
colvars: This is usually the result of an ill-defined set of atoms for rotational alignment (RMSD, rotateReference, etc).
FATAL ERROR: Error in the collective variables module (see above for details)
colvars: Too many iterations in routine jacobi.
colvars: This is usually the result of an ill-defined set of atoms for rotational alignment (RMSD, rotateReference, etc).
FATAL ERROR: Error in the collective variables module (see above for details)
colvars: Too many iterations in routine jacobi.
colvars: This is usually the result of an ill-defined set of atoms for rotational alignment (RMSD, rotateReference, etc).
FATAL ERROR: Error in the collective variables module (see above for details)
colvars: Too many iterations in routine jacobi.
colvars: This is usually the result of an ill-defined set of atoms for rotational alignment (RMSD, rotateReference, etc).
FATAL ERROR: Error in the collective variables module (see above for details)
FATAL ERROR: Error in the collective variables module (see above for details)
FATAL ERROR: Error in the collective variables module (see above for details)
FATAL ERROR: Error in the collective variables module (see above for details)
FATAL ERROR: Error in the collective variables module (see above for details)
FATAL ERROR: Error in the collective variables module (see above for details)

**Comment by groponp** [comment]
I'm running with NAMD 2.14 GPU and multicore

**Comment by fhh2626** [comment]
Please, use the latest version of NAMD because we always try to introduce latest features.

**Comment by groponp** [comment]
Thanks I can use namd3 for it task and report.

Em qui., 22 de jun. de 2023 12:44, Haohao Fu ***@***.***>
escreveu:

**Comment by groponp** [comment]
I'm using  NAMD (3.0b3), and when running 007.1 step of equilibration I'm getting it error 

FATAL ERROR: CudaTileListKernel::buildTileLists, maximum shared memory allocation exceeded. Too many atoms in a patch
FATAL ERROR: CudaTileListKernel::buildTileLists, maximum shared memory allocation exceeded. Too many atoms in a patch
[Partition 0][Node 0] End of program

**Comment by fhh2626** [comment]
> I'm using NAMD (3.0b3), and when running 007.1 step of equilibration I'm getting it error
> 
> FATAL ERROR: CudaTileListKernel::buildTileLists, maximum shared memory allocation exceeded. Too many atoms in a patch FATAL ERROR: CudaTileListKernel::buildTileLists, maximum shared memory allocation exceeded. Too many atoms in a patch [Partition 0][Node 0] End of program

This is weired. Can you use the same psf and pdb file for equilibration?

**Comment by groponp** [comment]
I am using the PSF and PDB generated in the previous step (007.0) called "largebox", and I get this error.

**Comment by fhh2626** [comment]
Could you send the generated files so that I can debug?

**Comment by groponp** [comment]
Hi,

I’ve fix it using NAMD3.0b with 12 cores.

Best.

Enviado de Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: Haohao Fu ***@***.***>
Enviado: Sunday, July 2, 2023 12:11:43 PM
Para: fhh2626/BFEE2 ***@***.***>
Cc: Ropón-Palacios G. ***@***.***>; Author ***@***.***>
Assunto: Re: [fhh2626/BFEE2] Error in Step 007 `Jacobi` (Issue #103)


Could you send the generated files so that I can debug?
