### ISSUE TITLE
Error with BFEE2Gui Generate Inputs button 

### ISSUE THREAD

**Issue by mglgc** [fhh2626/BFEE2#105]
Hi,
The BFEE2Gui.py Generate Inputs button is giving a window error whatever directory you select: "Selection correspond to nothing! Check your selection again!"
Please, could you give us some guide to fix it? Thank you very much in advance for your reply.

**Comment by fhh2626** [comment]
hi,

Please have a look at https://docs.mdanalysis.org/stable/documentation_pages/selections.html ,  and make a correct selection.

Good luck

**Comment by mglgc** [comment]
> hi,
> 
> Please have a look at https://docs.mdanalysis.org/stable/documentation_pages/selections.html , and make a correct selection.
> 
> Good luck

Thank you for your reply. I'm getting a bit confused with that. I can't figure out how to input some MDAnalysis selection command in the BFF2Gui.py window. Please, could you show me some proper example that help us to go ahead?
Thank you very much in advance.

**Comment by mglgc** [comment]
Hi,
Sorry for my last question. After a carefully reading in the BFEE2 original paper the Procedure 1, 4th Step, I could figured out where to input the segid for both protein and ligand. Thank you once again.
