### ISSUE TITLE
BFEE2Gui window Error after Procedure 1, Step 6

### ISSUE THREAD

**Issue by mglgc** [fhh2626/BFEE2#106]
Hi,
After clicking the Generate Inputs button in the BFEE2Gui Pre-treatment tab, an error window is showed containing the following text:
"Unknown error! The error message is: The true value of an array with more than one element is ambiguous. Use a.any() or a.all()"

Please, could you point us to the meaning of such an error message in order we can deal with it? Thank you very much in advance for your reply.

**Comment by fhh2626** [comment]
Were you using the latest version of BFEE2 (2.4.0)?

**Comment by mglgc** [comment]
> Were you using the latest version of BFEE2 (2.4.0)?

Thank you for your reply. Because  I have installed BFEE2 through conda, I'm using the latest version.

**Comment by fhh2626** [comment]
This is weird. You can send me your input files if possible.

**Comment by rez3vil** [comment]
I ran into the same error. Following was the snippet in the terminal

```shell
Info) Using plugin pdb for coordinates from file ./ligandOnly.pdb
Info) Finished with coordinate file ./ligandOnly.pdb.
2
atomselect6
atomselect7
Info) Opened coordinate file ./ligandOnly.xyz for writing.
Info) Finished with coordinate file ./ligandOnly.xyz.
Info) Opened coordinate file fep_ligandOnly.pdb for writing.
Info) Finished with coordinate file fep_ligandOnly.pdb.
Info) VMD for LINUXAMD64, version 1.9.4a57 (April 27, 2022)
Info) Exiting normally.
vmd > /home/administrator/anaconda3/envs/bfee2/lib/python3.11/site-packages/MDAnalysis/topology/PDBParser.py:348: UserWarning: Unknown element  found for some atoms. These have been given an empty element record. If needed they can be guessed using MDAnalysis.topology.guessers.
  warnings.warn(wmsg)
/home/administrator/anaconda3/envs/bfee2/lib/python3.11/site-packages/MDAnalysis/topology/guessers.py:146: UserWarning: Failed to guess the mass for the following atom types: 
  warnings.warn("Failed to guess the mass for the following atom types: {}".format(atom_type))
/home/administrator/anaconda3/envs/bfee2/lib/python3.11/site-packages/MDAnalysis/coordinates/PDB.py:451: UserWarning: 1 A^3 CRYST1 record, this is usually a placeholder. Unit cell dimensions will be set to None.
  warnings.warn("1 A^3 CRYST1 record,"
The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

```

**Comment by mglgc** [comment]
> This is weird. You can send me your input files if possible.

I'm attaching the files zip compressed. Thank you very much in advance for your help and reply.
[files.zip](https://github.com/fhh2626/BFEE2/files/11957742/files.zip)

**Comment by fhh2626** [comment]
@mglgc @rez3vil I cannot reproduce your error. Did you make the correct selections of the protein and the ligand, and use the latest version of VMD (1.9.4)?
![Screenshot 2023-07-07 141518](https://github.com/fhh2626/BFEE2/assets/25058290/bf67e52a-3fcd-42e5-a2b0-cdf05ca141b2)

**Comment by rez3vil** [comment]
@fhh2626 Hi, I am trying to reproduce the result with the same files from supplementary data from your nature articles, so all input files are same. I have installed the latest version of vmd. Last week I got the error around atomselect6, today it's around atomselect13.

![Screenshot from 2023-07-11 11-56-06_cropped](https://github.com/fhh2626/BFEE2/assets/125429015/ce60107f-433f-4cff-907e-0e0e3465c4be)

I am attaching the files for the same.
[Workflow_geometrical.zip](https://github.com/fhh2626/BFEE2/files/12011380/Workflow_geometrical.zip)

**Comment by fhh2626** [comment]
@mglgc @rez3vil I think that the problem is caused by the different behavior between distict version of numpy. Please download the latest devel branch and tell me if it fixed this issue.

**Comment by rez3vil** [comment]
> @mglgc @rez3vil I think that the problem is caused by the different behavior between distict version of numpy. Please download the latest devel branch and tell me if it fixed this issue.

Hi, I am using the latest numpy version 1.25.1, issue still exists. I have tried with Alchemical pathway too, the same error.

```python
atomselect6
atomselect7
Info) Opened coordinate file ./ligandOnly.xyz for writing.
Info) Finished with coordinate file ./ligandOnly.xyz.
Info) Opened coordinate file fep_ligandOnly.pdb for writing.
Info) Finished with coordinate file fep_ligandOnly.pdb.
Info) VMD for LINUXAMD64, version 1.9.4a57 (April 27, 2022)
Info) Exiting normally.
vmd > /home/administrator/anaconda3/envs/bfee2/lib/python3.11/site-packages/MDAnalysis/topology/PDBParser.py:348: UserWarning: Unknown element  found for some atoms. These have been given an empty element record. If needed they can be guessed using MDAnalysis.topology.guessers.
  warnings.warn(wmsg)
/home/administrator/anaconda3/envs/bfee2/lib/python3.11/site-packages/MDAnalysis/topology/guessers.py:146: UserWarning: Failed to guess the mass for the following atom types: 
  warnings.warn("Failed to guess the mass for the following atom types: {}".format(atom_type))
/home/administrator/anaconda3/envs/bfee2/lib/python3.11/site-packages/MDAnalysis/coordinates/PDB.py:451: UserWarning: 1 A^3 CRYST1 record, this is usually a placeholder. Unit cell dimensions will be set to None.
  warnings.warn("1 A^3 CRYST1 record,"
The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

**Comment by fhh2626** [comment]
@rez3vil Well, I mean the devel branch of BFEE2. You can download it, move `./bin/BFEE2Gui.py` to `./BFEE2Gui.py` and run `python BFEE2Gui.py`.

**Comment by mglgc** [comment]
> @rez3vil Well, I mean the devel branch of BFEE2. You can download it, move `./bin/BFEE2Gui.py` to `./BFEE2Gui.py` and run `python BFEE2Gui.py`.

Hi,
Where can we get the BFEE2 devel branch for installing?
Thank you in advance for your reply.

**Comment by Naiveskii** [comment]
I meet the same error, but when I generate the Gromacs input, it works. Only use it to generate the NAMD input files occurred such error.

> @rez3vil Well, I mean the devel branch of BFEE2. You can download it, move `./bin/BFEE2Gui.py` to `./BFEE2Gui.py` and run `python BFEE2Gui.py`.

And you mean just move the BFEE2Gui.py out of the folder bin/ to the main directory and run it with command 'python BFEE2Gui.py' after download the devel branch and unzip it? I tried, but return the error: 
`Traceback (most recent call last):
  File "BFEE2Gui.py", line 11, in <module>
    from PySide2.QtWidgets import QApplication
ImportError: No module named PySide2.QtWidgets`
It seems that some of dependences is missing. After following the error tips and installing all dependencies, it still does not function and return the error: 
`The X11 connection broke: Maximum allowed requested length exceeded (code 4)
X connection to localhost:10.0 broken (explicit kill or server shutdown).`

**Comment by rez3vil** [comment]
> @rez3vil Well, I mean the devel branch of BFEE2. You can download it, move `./bin/BFEE2Gui.py` to `./BFEE2Gui.py` and run `python BFEE2Gui.py`.

Okay this worked, thank you very much! Files are generated successfully now for NAMD. 

> Hi, Where can we get the BFEE2 devel branch for installing? Thank you in advance for your reply.

You can switch to "dev" branch from the homepage of BFEE2, if you still can't find it, use this link. "[https://github.com/fhh2626/BFEE2/tree/dev](https://github.com/fhh2626/BFEE2/tree/dev)". 

> And you mean just move the BFEE2Gui.py out of the folder bin/ to the main directory and run it with command 'python BFEE2Gui.py' after download the devel branch and unzip it?

If you are using linux, just locate the changed file, which was "configTemplate.py" and replace it from the devel zip file in respective folder.

**Comment by Naiveskii** [comment]
@mglgc @rez3vil Well, I have solved the problem. Just follow the advice of @fhh2626, download the devel branch of BFEE2 and unzip it, enter the folder and find the file ./BFEE2/templates_namd/configTemplate.py, copy it to this directory: /home/xxxx/anaconda3/envs/bfee/lib/python3.11/site-packages/BFEE2/templates_namd, this is the conda environment which you install the BFEE2. Then run the BFEE2Gui.py and set as the tutorial said.

**Comment by Naiveskii** [comment]
> > @rez3vil Well, I mean the devel branch of BFEE2. You can download it, move `./bin/BFEE2Gui.py` to `./BFEE2Gui.py` and run `python BFEE2Gui.py`.
> 
> @fhh2626 Okay devel branched BFEE2 worked, thank you very much! Files are generated successfully now for NAMD. I replaced "configTemplate.py" file alone.
> 
> > Hi, Where can we get the BFEE2 devel branch for installing? Thank you in advance for your reply.
> 
> @mglgc You can switch to "dev" branch from the homepage of BFEE2, if you still can't find it, use this link. "https://github.com/fhh2626/BFEE2/tree/dev".
> 
> > And you mean just move the BFEE2Gui.py out of the folder bin/ to the main directory and run it with command 'python BFEE2Gui.py' after download the devel branch and unzip it?
> 
> @Naiveskii If you are using linux, just locate the changed file, which was "configTemplate.py" and replace it from the devel zip file in respective folder.

I find it works in same the way just now.😂 When I finish typing the words and sent it out, I found that you have already solved it. Anyway, Thank you for telling us this solution. :)

**Comment by mglgc** [comment]
> > > @rez3vil Well, I mean the devel branch of BFEE2. You can download it, move `./bin/BFEE2Gui.py` to `./BFEE2Gui.py` and run `python BFEE2Gui.py`.
> > 
> > 
> > @fhh2626 Okay devel branched BFEE2 worked, thank you very much! Files are generated successfully now for NAMD. I replaced "configTemplate.py" file alone.
> > > Hi, Where can we get the BFEE2 devel branch for installing? Thank you in advance for your reply.
> > 
> > 
> > @mglgc You can switch to "dev" branch from the homepage of BFEE2, if you still can't find it, use this link. "https://github.com/fhh2626/BFEE2/tree/dev".
> > > And you mean just move the BFEE2Gui.py out of the folder bin/ to the main directory and run it with command 'python BFEE2Gui.py' after download the devel branch and unzip it?
> > 
> > 
> > @Naiveskii If you are using linux, just locate the changed file, which was "configTemplate.py" and replace it from the devel zip file in respective folder.
> 
> I find it works in same the way just now.joy When I finish typing the words and sent it out, I found that you have already solved it. Anyway, Thank you for telling us this solution. :)

That fix works for me too for the geometrical route (not tested yet for the alchemical one). Thank you!
