### ISSUE TITLE
error when distributing on PyPI

### ISSUE THREAD

**Issue by fhh2626** [fhh2626/BFEE2#109]
@HanatoK 
I got the error when distributing BFEE 2,4.1:
```
python setup.py sdist bdist_wheel
twine upload dist/*
```

```
Uploading BFEE2-2.4.1-py3-none-any.whl
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 246.6/246.6 kB • 00:01 • 230.2 kB/s
WARNING  Error during upload. Retry with the --verbose option for more details.
ERROR    HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/
         Wheel 'BFEE2-2.4.1-py3-none-any.whl' does not contain the required METADATA file:
         bfee2-2.4.1.dist-info/METADATA
```

Is there something new for setuptools that we are missing?

**Comment by HanatoK** [comment]
I am not sure. Someone else on SO encountered the same problem today:
https://stackoverflow.com/questions/76756635/pypi-twine-missing-metadata-but-it-exists-in-whl-file

**Comment by HanatoK** [comment]
I don't know why PyPI becomes case-sensitive about the package name. Could you try to change the name in `setup.cfg` to lower case (`name = bfee2`)?

**Comment by fhh2626** [comment]
It works, thank!
