### ISSUE TITLE
FATAL ERROR: CUDA error in ComputeBondedCUDA

### ISSUE THREAD

**Issue by shradheyagupta** [fhh2626/BFEE2#115]
FATAL ERROR: CUDA error in ComputeBondedCUDA:: forceDoneCheck after polling 13 times over 0.001407 s on Pe 4 (iks device 0 pci 0:1:0): an illegal memory access was encountered

I have proviously cauculated the binding free energy using BFEE2 tool but in another calculation which has lone pairs the above error is coming.

**Comment by fhh2626** [comment]
See #116
