### ISSUE TITLE
FATAL ERROR: Periodic cell has become too small for original patch grid!

### ISSUE THREAD

**Issue by shradheyagupta** [fhh2626/BFEE2#117]
FATAL ERROR: Periodic cell has become too small for original patch grid!
There are probably many margin violations already reported.
Possible solutions are to restart from a recent checkpoint, increase margin, or disable useFlexibleCell for liquid simulation.

I have increased the margin, disable useFlexibleCell still it is showing the same error.

**Comment by fhh2626** [comment]
This issue may have many reasons. Have a look at your trajectory and see if there is something wrong. Maybe a reequilibration or remodeling can address this issue.

**Comment by shradheyagupta** [comment]
trajectory file looks ok, after restarting the issue gets resolved.
