### ISSUE TITLE
colvars2.in does not exist!

### ISSUE THREAD

**Issue by shradheyagupta** [fhh2626/BFEE2#118]
I am using the alchemical route for NAMD. as suggested in the readme file I run the 000.3_updateCenters.py in the 000_eq folder after completion of 000.1_eq.conf but the first line of the message shows that the "colvars2.in does not exist!" . Rest all files are updated

The files I have in the 000_eq folder are colvars.in and colvars_ligandOnly.in
<img width="285" alt="Screenshot 2024-01-05 at 7 30 40 PM" src="https://github.com/fhh2626/BFEE2/assets/61943583/87eb1d11-6f6a-430f-a59a-d7bd56d8c10e">

**Comment by fhh2626** [comment]
This is fine. I will suppress this warning in the next release.
