### ISSUE TITLE
sh: 15: hash: Illegal option -t

### ISSUE THREAD

**Issue by ljh433** [fhh2626/BFEE2#126]
Thank you for your contributions. when i Patch Gromacs with Colvars (sh ./colvars-master/update-colvars-code.sh ./gromacs-2020.6)，there is an error：./colvars-master/update-colvars-code.sh: 15: hash: Illegal option -t. May I ask what the reason is. How to solve this problem？

**Comment by HanatoK** [comment]
Hi @ljh433! This should be an issue of Colvars. Please open the issue in https://github.com/Colvars/colvars/.

**Comment by ljh433** [comment]
Thanks

---- Replied Message ----
| From | ***@***.***> |
| Date | 05/26/2024 23:28 |
| To | fhh2626/BFEE2 ***@***.***> |
| Cc | Jh ***@***.***>,
Mention ***@***.***> |
| Subject | Re: [fhh2626/BFEE2] sh: 15: hash: Illegal option -t (Issue #126) |

Hi @ljh433! This should be an issue of Colvars. Please open the issue in https://github.com/Colvars/colvars/.
