### ISSUE TITLE
 Supplementary Data acquisition

### ISSUE THREAD

**Issue by ljh433** [fhh2626/BFEE2#127]
Thank you for your contributions. The article(doi: 10.1038/s41596-021-00676-1) says it provides example data，but I couldn't find any supplementary materials. May I ask if you can provide it? This example data is important for me as a beginner to learn。
![123](https://github.com/fhh2626/BFEE2/assets/68458327/0771a754-7e49-442e-bd9f-34c07426bbad)

**Comment by fhh2626** [comment]
I suspect you can immediately see the download link after clicking this "Supplementary Data" hyperlink.

**Comment by ljh433** [comment]
Thank you for your prompt reply.when i click this "Supplementary Data" hyperlink，it will redirect to this page. But this page only has one PDF supplementary material.
![image](https://github.com/fhh2626/BFEE2/assets/68458327/96af9c53-cf4e-4352-9943-9748615cab67)

**Comment by fhh2626** [comment]
Please, download the files from the official site (https://www.nature.com/articles/s41596-021-00676-1). Pubmed is only a third-party service.

**Comment by ljh433** [comment]
Thank you for Professor Fu's reminder. I have found it.
