### ISSUE TITLE
Test about cross-platform ability of BFEE2

### ISSUE THREAD

**Issue by fhh2626** [fhh2626/BFEE2#42]
- [ ] Install through pip on windows
- [x] Install through conda on windows
- [ ] Install through pip on Ubuntu
- [x] Install through conda on Ubuntu
- [ ] Install through pip on MacOS
- [x] Install through conda on MacOS
- [ ] Install through pip on OpenSUSE
- [x] Install through conda on OpenSUSE
- [x] Generate CHARMM files of a globular protein on Windows
- [x] Generate CHARMM files of a membrane protein on Windows
- [x] Generate Amber files of a globular protein on Windows
- [x] Generate Gromacs files of a globular protein on Windows
- [x] Post-treat alchemical files on Windows
- [x] Post-treat geometrical files on Windows
- [x] Merge files on Windows
- [x] Quick-plot files on Windows
- [x] Plot time evolution of RMSD on Windows
- [x] Help on windows
- [x] Generate CHARMM files of a globular protein on Ubuntu
- [x] Generate CHARMM files of a membrane protein on Ubuntu
- [x] Generate Amber files of a globular protein on Ubuntu
- [x] Generate Gromacs files of a globular protein on Ubuntu
- [x] Post-treat alchemical files on Ubuntu
- [x] Post-treat geometrical files on Ubuntu
- [x] Merge files on Ubuntu
- [x] Quick-plot files on Ubuntu
- [x] Plot time evolution of RMSD on Ubuntu
- [x] Help on Ubuntu
- [x] Generate CHARMM files of a globular protein on MacOS
- [x] Generate CHARMM files of a membrane protein on MacOS
- [x] Generate Amber files of a globular protein on MacOS
- [x] Generate Gromacs files of a globular protein on MacOS
- [x] Post-treat alchemical files on MacOS
- [x] Post-treat geometrical files on MacOS
- [x] Merge files on MacOS
- [x] Quick-plot files on MacOS
- [x] Plot time evolution of RMSD on MacOS
- [x] Help on MacOS
- [x] Generate CHARMM files of a globular protein on OpenSUSE
- [x] Generate CHARMM files of a membrane protein on OpenSUSE
- [x] Generate Amber files of a globular protein on OpenSUSE
- [x] Generate Gromacs files of a globular protein on OpenSUSE
- [x] Post-treat alchemical files on OpenSUSE
- [x] Post-treat geometrical files on OpenSUSE
- [x] Merge files on OpenSUSE
- [x] Quick-plot files on OpenSUSE
- [x] Plot time evolution of RMSD on OpenSUSE
- [x] Help on OpenSUSE

**Comment by HanatoK** [comment]
Please be sure using the conda version of BFEE for testing, since that's the final distributed version.

**Comment by fhh2626** [comment]
> @fhh2626
> Please be sure using the conda version of BFEE for testing in a clean python environment, since that's the final distributed version.
> 
> ```
> $ conda create --name bfee_testing
> $ conda activate bfee_testing
> $ conda install -c conda-forge BFEE2
> ```
> 
> You may need to upload new sdist and bdist to pip, and then update the conda recipe to rebuild the package on conda-forge.
> After testing, the environment can be deleted by `conda remove -n bfee_testing --all`.

OK, I unchecked the items. But that means we need to distribute before testing?

**Comment by HanatoK** [comment]
> > @fhh2626
> > Please be sure using the conda version of BFEE for testing in a clean python environment, since that's the final distributed version.
> > ```
> > $ conda create --name bfee_testing
> > $ conda activate bfee_testing
> > $ conda install -c conda-forge BFEE2
> > ```
> > 
> > 
> > You may need to upload new sdist and bdist to pip, and then update the conda recipe to rebuild the package on conda-forge.
> > After testing, the environment can be deleted by `conda remove -n bfee_testing --all`.
> 
> OK, I unchecked the items. But that means we need to distribute before testing?

Yes, I think so. You can release a new version on pypi, and then update the version number and hash in https://github.com/conda-forge/bfee2-feedstock.

**Comment by fhh2626** [comment]
> > > @fhh2626
> > > Please be sure using the conda version of BFEE for testing in a clean python environment, since that's the final distributed version.
> > > ```
> > > $ conda create --name bfee_testing
> > > $ conda activate bfee_testing
> > > $ conda install -c conda-forge BFEE2
> > > ```
> > > 
> > > 
> > > You may need to upload new sdist and bdist to pip, and then update the conda recipe to rebuild the package on conda-forge.
> > > After testing, the environment can be deleted by `conda remove -n bfee_testing --all`.
> > 
> > 
> > OK, I unchecked the items. But that means we need to distribute before testing?
> 
> Yes, I think so. You can release a new version on pypi, and then update the version number and hash in https://github.com/conda-forge/bfee2-feedstock.

OK, I'll do it later. Before that, do we want to add PySide2 back as a dependency in pypi？

**Comment by HanatoK** [comment]
@fhh2626 
You can add it if it works. Anyway, the dependencies of the conda package can be different from the pypi one, and I have already required PySide2 in the conda version.

**Comment by fhh2626** [comment]
@HanatoK could you plz test the OpenSUSE compatibility, as you are using it?

**Comment by fhh2626** [comment]
> @HanatoK could you plz test the OpenSUSE compatibility, as you are using it?

Note that both the alchemical and geometrical routes should be tested

**Comment by fhh2626** [comment]
@HanatoK Can you use pip to install BFEE2 without preparing the dependency with conda? The pip version of pyside2 seems broken on some platform.

**Comment by HanatoK** [comment]
@fhh2626 
Installation through PyPI misses the execution bit of BFEE2Gui.py. That's trivial but if you want to fix it you need to package the binary distribution in a POSIX-compliant environment.

**Comment by HanatoK** [comment]
@fhh2626 
You need to test the PyPI package in a clean python virtual environment to avoid the hassle with system packages. The pyside2 from PyPI works well in virtualenv.

**Comment by fhh2626** [comment]
@HanatoK Could you please test the new quick-plot and merge of the dev branch on OpenSUSE? Maybe you can merge it to the main branch and upload a new pip package, hence addressing the execution bit issue.

- [ ] quick-plot and merge on Windows
- [ ] quick-plot and merge on Ubuntu
- [ ] quick-plot and merge on MacOS
- [ ] quick-plot and merge on OpenSUSE

**Comment by HanatoK** [comment]
@fhh2626 I am not a maintainer of the BFEE package on PyPI.
