### ISSUE TITLE
HINT/command for output redirection missing?

### ISSUE THREAD

**Issue by ReneHamburger1993** [fhh2626/BFEE2#66]
Hi
I tried to use the GUI with my Ligand + Protein setup  with GROMACS:

000_eq worked fine and produced output directly inside 000_eq NOT inside 000_eq/output
and the suffix .out was missing

002_euler_theta I could not generate its tpr file until I copied the output from 000_eq/000_eq.* to 000_eq/output and renamed the to have the `.out` prefix

Though if I am not mistaken either output redirection/renaming (hint) is missing or just the path at [these lines](https://github.com/fhh2626/BFEE2/blob/9a3391bbf2498a4d300cf4e701f168cb2f12ff7e/BFEE2/templates_gromacs/BFEEGromacs.py#L599) are wrong.

Cheers
René

**Comment by fhh2626** [comment]
Did you use *.sh in the corresponding folder to generate tpr files? It will also show the command of submission that redirects the output correctly.

**Comment by ReneHamburger1993** [comment]
okay I just overlooked this one. Just getting used to gromacs. Thanks!
