### ISSUE TITLE
differences in NAMD and GROMACS setups

### ISSUE THREAD

**Issue by ReneHamburger1993** [fhh2626/BFEE2#67]
Hi,

what is the reason that in 
               NAMD       colvars files `hillWeight  0.05` is used 
while for GROMACS colvars files `hillWeight 0.2092` is used?

Cheers
René

**Comment by fhh2626** [comment]
Because NAMD uses kcal while Gromacs uses kJ as the unit of energy internally.

Haohao

**Comment by ReneHamburger1993** [comment]
I see thanks for clarification! :)
