### ISSUE TITLE
BFEEGromacs does not work under Windows 11

### ISSUE THREAD

**Issue by fhh2626** [fhh2626/BFEE2#70]
2021-07-13 16:03:31,250 [BFEEGromacs][007][INFO]:Generating simulation files for D://BFEE/007_r...
2021-07-13 16:03:31,250 [BFEEGromacs][007][INFO]:Making directory D:\miniconda3\Scripts/D:/BFEE/007_r...
[WinError 123]

I suspect this is due to the use of posixpath in BFEEGromacs, which should always be replaced by os.path @HanatoK

**Comment by fhh2626** [comment]
@HanatoK I have simply used "os.path" to replace all the "posixpath" of BFEEGromacs and it works under my laptop (Windows 11). You may want to have a look and test #71 before merging.

**Comment by HanatoK** [comment]
The python code work in Windows 10:
![img](https://imgur.com/i6rzvym.png)

Which line is actually causing the bug?

**Comment by fhh2626** [comment]
It works on Windows 10 but not Windows 11.
`self.logger.info(f'Making directory {os.path.abspath(generate_basename)}...')`
is already wrong. I suspect
`self.baseDirectory`
is also wrong.

**Comment by HanatoK** [comment]
> It works on Windows 10 but not Windows 11.
> `self.logger.info(f'Making directory {os.path.abspath(generate_basename)}...')`
> is already wrong. I suspect
> `self.baseDirectory`
> is also wrong.

It may be a bug of Windows 11 or the `os` module in Python. Windows 11 is still in preview stage and may not be compatible with Python. Perhaps issuing a bug report on MSDN or contacting the technical support of Microsoft is better.

By the way, I have tested on a clean Windows 11 installation in a virtual machine, but everything works fine.
![img](https://i.imgur.com/B4PH5P7.png)

**Comment by fhh2626** [comment]
> > It works on Windows 10 but not Windows 11.
> > `self.logger.info(f'Making directory {os.path.abspath(generate_basename)}...')`
> > is already wrong. I suspect
> > `self.baseDirectory`
> > is also wrong.
> 
> It may be a bug of Windows 11 or the `os` module in Python. Windows 11 is still in preview stage and may not be compatible with Python. Perhaps issuing a bug report on MSDN or contacting the technical support of Microsoft is better.
> 
> By the way, I have tested on a clean Windows 11 installation in a virtual machine, but everything works fine.
> ![img](https://camo.githubusercontent.com/ef68df458e461512316253a18327375e031b25529dceb2f269b1f24d0f41ea57/68747470733a2f2f692e696d6775722e636f6d2f423450483550372e706e67)

I don't think so. According to Python documentation, the behavior of `posixpath` under Windows is not well defined. We should not blame too much about Windows 11. We are supposed to use `os.path` to circumvent the issue.

As for your picture, are you sure there is no problem (considering the following path)? 
![1626267616(1)](https://user-images.githubusercontent.com/25058290/125626206-2b4aa815-2a65-4345-babc-069082ceef87.jpg)

**Comment by HanatoK** [comment]
> > > It works on Windows 10 but not Windows 11.
> > > `self.logger.info(f'Making directory {os.path.abspath(generate_basename)}...')`
> > > is already wrong. I suspect
> > > `self.baseDirectory`
> > > is also wrong.
> > 
> > 
> > It may be a bug of Windows 11 or the `os` module in Python. Windows 11 is still in preview stage and may not be compatible with Python. Perhaps issuing a bug report on MSDN or contacting the technical support of Microsoft is better.
> > By the way, I have tested on a clean Windows 11 installation in a virtual machine, but everything works fine.
> > ![img](https://camo.githubusercontent.com/ef68df458e461512316253a18327375e031b25529dceb2f269b1f24d0f41ea57/68747470733a2f2f692e696d6775722e636f6d2f423450483550372e706e67)
> 
> I don't think so. According to Python documentation, the behavior of `posixpath` under Windows is not well defined. We should not blame too much about Windows 11. We are supposed to use `os.path` to circumvent the issue.
> 
> As for your picture, are you sure there is no problem (considering the following path)?
> ![1626267616(1)](https://user-images.githubusercontent.com/25058290/125626206-2b4aa815-2a65-4345-babc-069082ceef87.jpg)

It looks like a problem of logging by `posixpath.abspath` but the actual code works since there is no `posixpath.abspath` involved in the call of `os.makedirs`. Why using `posixpath` in this case is a problem on Windows? Any documentation?

The most noticable behavior of `posixpath` is the use of forward slash, which contradicts the convention of Windows, but since Windows API also accepts forward slash as path separator (https://en.wikipedia.org/wiki/Backslash#Filenames), I think it is OK to use it.

**Comment by fhh2626** [comment]
> > > > It works on Windows 10 but not Windows 11.
> > > > `self.logger.info(f'Making directory {os.path.abspath(generate_basename)}...')`
> > > > is already wrong. I suspect
> > > > `self.baseDirectory`
> > > > is also wrong.
> > > 
> > > 
> > > It may be a bug of Windows 11 or the `os` module in Python. Windows 11 is still in preview stage and may not be compatible with Python. Perhaps issuing a bug report on MSDN or contacting the technical support of Microsoft is better.
> > > By the way, I have tested on a clean Windows 11 installation in a virtual machine, but everything works fine.
> > > ![img](https://camo.githubusercontent.com/ef68df458e461512316253a18327375e031b25529dceb2f269b1f24d0f41ea57/68747470733a2f2f692e696d6775722e636f6d2f423450483550372e706e67)
> > 
> > 
> > I don't think so. According to Python documentation, the behavior of `posixpath` under Windows is not well defined. We should not blame too much about Windows 11. We are supposed to use `os.path` to circumvent the issue.
> > As for your picture, are you sure there is no problem (considering the following path)?
> > ![1626267616(1)](https://user-images.githubusercontent.com/25058290/125626206-2b4aa815-2a65-4345-babc-069082ceef87.jpg)
> 
> It looks like a problem of logging by `posixpath.abspath` but the actual code works since there is no `posixpath.abspath` involved in the call of `os.makedirs`. Why using `posixpath` in this case is a problem on Windows? Any documentation?
> 
> The most noticable behavior of `posixpath` is the use of forward slash, which contradicts the convention of Windows, but since Windows API also accepts forward slash as path separator (https://en.wikipedia.org/wiki/Backslash#Filenames), I think it is OK to use it.

OK, to address this issue. I simply replaced `posixpath.abspath` and `posixpath.relpath` to the counterparts of `os.path` in #73 . The generated files look good in my computer.
