### ISSUE TITLE
BFEE2 tutorial

### ISSUE THREAD

**Issue by almeida85** [fhh2626/BFEE2#76]
Hello,

Is there any tutorial to learn how to use BFEE2?

In a previous issue (#56) protein-protein calculation is not implemented. Is it yet? Should I use the approach you suggested in the issue to compute the binding free energy of a protein complex?

Thanks in advance.

**Comment by fhh2626** [comment]
> 

@almeida85 . There will be a tutorial (Nature Protocols, 2022, doi: 10.1038/s41596-021-00676-1). It is in press currently.

Best,
Haohao
