### ISSUE TITLE
Asking BFEE2 

### ISSUE THREAD

**Issue by purnawanpp** [fhh2626/BFEE2#92]
On page 1126-1127 chapter 10 of your journal you change the center to -2: 
harmonic {
colvars eulerTheta
forceConstant 0.1
centers -2.0
}

what I want to ask here is whether the value centers -2 applies to all simulated systems?

**Comment by fhh2626** [comment]
Yes. You can also use 000.5_updateCenters.py to do it automatically based on the results of the equilibration.

**Comment by purnawanpp** [comment]
thank you
