### ISSUE TITLE
forceconstant values for free energy calculations 

### ISSUE THREAD

**Issue by ndonyapour** [fhh2626/BFEE2#93]
Hello,

I'm running simulations using your method (BFEE2) and I have a question about the `forceconstant` value in the free energy calculation function (e.g. `geometricRestraintContribution`).  Is this the force constant defined for each harmonic restraint or is it the scaled value of it (`forceconstant` is scaled according to the specified width)?

Thank you!

**Comment by fhh2626** [comment]
Hi ndonyapour,

In BFEE2, whenever a `harmonic` block is defined, the `width` is not specified for the corresponding CV, which imply that the `forceConstant` is exactly k.

Haohao

**Comment by ndonyapour** [comment]
Thank you for response! I thought you use the force constant from `harmonicWalls`.

**Comment by fhh2626** [comment]
That's another story. The force constant from `harmonicWalls` guatantees sampling within the current window and should not affect the result. You can also use an reflecting boundary whenever you want.

**Comment by ndonyapour** [comment]
That explains why. Thank you for your quick response!
