### ISSUE TITLE
Installation of BFEE2 with conda failed.

### ISSUE THREAD

**Issue by Tangbbmc** [fhh2626/BFEE2#95]
I failed to install BFEE2 by conda with the following command: conda install -c conda-forge bfee2 .

(base) PS C:\Users\tangw> conda install -c conda-forge bfee2
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

**Comment by HanatoK** [comment]
Hi @Tangbbmc ,
Could you try installing bfee2 in a new Conda environment? For example,
```
conda create -n bfee2
conda activate bfee2
conda install -c conda-forge bfee2
```

**Comment by Tangbbmc** [comment]
@HanatoK It really works! Thank you for your kind help!
