### ISSUE TITLE
Question: update centers

### ISSUE THREAD

**Issue by ReneHamburger1993** [fhh2626/BFEE2#98]
Hi, I got a question about the statement:
"To calculate the binding free energy:

1.1   run 000_eq/000.1_eq.conf
1.2.  (optionally) run 000_eq/000.2_updateCenters.py
      **(If this is done, then there is usually no need to change restraining centers
       after steps 3.x.)**"

I am a litte confused by the word "after". What does "**after** steps 3.x." actually mean?
Do I need to update the centers again with the position of the respective PMF minima when using the `000_eq/000.2_updateCenters.py` pyscript or not?

`https://github.com/fhh2626/BFEE2/blob/92352ae884d4499f27885d013410852370495f0f/BFEE2/templates_readme/Readme_NAMD_Geometrical.txt`

**Comment by ReneHamburger1993** [comment]
Point being, I would not need to write some lines of code to automate this and can just pass my generated jobscripts to the cluster in dependence or even run the angle abf runs in parallel as well if no update was necessary.

**Comment by fhh2626** [comment]
> Point being, I would not need to write some lines of code to automate this and can just pass my generated jobscripts to the cluster in dependence or even run the angle abf runs in parallel as well if no update was necessary.

000.2_updateCenters.py updates the restraining centers using the results of the equilibration. You can then submit jobs one by one without change config files.

**Comment by ReneHamburger1993** [comment]
Okay thanks for the clarification! 👍 (A little textual update in that readme file above might help others as well)
